version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '19:00'
      timezone: 'Asia/Tokyo'
    versioning-strategy: auto

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '19:00'
      timezone: 'Asia/Tokyo'
